version: "3"
services:
  php:
     build:
       context: .
       dockerfile: data/php/Dockerfile
       args:
           TIMEZONE: ${TIMEZONE}
     volumes:
       - ./data/php:/var/www/certbot/phpDir/:rw
       - ./data/certbot/www:/var/www/certbot/
     expose:
       - 9000
     networks:
       - default
  nginx:
     image: nginx:1.15-alpine
     expose:
       - "80"
       - "443"
     ports:
       - "80:80"
       - "443:443"
     networks:
       - default
     volumes:
       - ./data/nginx:/etc/nginx/conf.d/:rw
       - ./data/certbot/conf:/etc/letsencrypt/:rw
       - ./data/certbot/www:/var/www/certbot/:rw
       - ./data/nginx/node:/var/www/certbot/phpDir/:rw
     command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  mongodb:
     image: mongo:4.4.11-rc0-focal
     volumes:
       - ./data/db_app:/var/lib/mongodb:rw
     ports:
       - "27017:27017"
     networks:
       - default
  node:
     build:
       context: .
       dockerfile: data/nginx/node/Dockerfile
     volumes:
       - ./data/nginx/node/:/root/app/:rw
       - ./data/certbot/www:/var/www/certbot/
       - ./data/certbot/conf:/etc/letsencrypt/:rw
     expose:
       - 3000
     ports:
       - "3000:3000"
     networks:
       - default
     depends_on:
       - nginx
       - php

  ##############################
# Certbot Container
##############################
  certbot:
     image: certbot/certbot:latest
     volumes:
       - ./data/certbot/conf:/etc/letsencrypt/:rw
       - ./data/certbot/www:/var/www/certbot/:rw
     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
